### PR TITLE
api: getuserstat

### PR DESCRIPTION
**Pull request by LinusU**
Hi,

This is some refactoring and making some interesting stats available thru the api.

It will require at least PHP 5.3 since I made use of namespaces, if this is non-negotiable I'll update the pq to not use namespaces.

Happy coding!

### CODE REVIEW

**Comment by wizkid057** [comment]
This is probably going to need a little more testing before I put it live, just in case.

**Comment by wizkid057** [comment]
Looks like some errors...

PHP Parse error:  syntax error, unexpected T_ENCAPSED_AND_WHITESPACE, expecting T_STRING or T_VARIABLE or T_NUM_STRING in userstats.php on line 404

**Comment by LinusU** [comment]
Shit must have missed that, hmm I thought that I ran it thru php to syntax check... Pushing new commit now!

**Comment by LinusU** [comment]
I `--amend`-ed my commit and `push --force`-ed it, it shouldn't have any syntax errors no more

**Comment by LinusU** [comment]
I do understand on the testing thought. How about we only update `api.php` and add `lib.userstat.php` for now. That way we won't alter any existing functionality but we can still test if my functions in `lib.userstat.php` works by using the api. Win win! :v:

**Comment by wizkid057** [comment]
I got caught up with other things when working on merging this for just the API.  Hopefully get to that today.

**Comment by mtab3000** [comment]
hi wizkid,

i´m a consultant at bmw. load and performance are my central topics.

if you need advice on dos or ddos prevention, let me know.

i appreciate your efforts for eligius very much.

don´t get panicked and driven to bad decisions.
keep the wallets online or chain them…
nobody cares for app layer. mining has to go on.

regards,
marko

Am 25.11.2013 um 01:41 schrieb wizkid057 notifications@github.com:

> Merged #47.
> 
> —
> Reply to this email directly or view it on GitHub.

Marko Taborsky
mtab@gmx.net

**Pull request merged**
