### PR TITLE
api: allow username in getacceptedcount

### PR DESCRIPTION
**Pull request by LinusU**
This allows passing a username instead of user_id to the `getacceptedcount` in the api.

I can't figure out my user id and thus currently cannot get any data from this function. A fast merge would be appreciated since I'm working on a small project at the moment and can't really continue without this :)

Thanks!

### CODE REVIEW

**Comment by wizkid057** [comment]
There was a reason why I used user_id..... but I can't recall it.

**Comment by LinusU** [comment]
Well, this patch only adds functionality. I have really tried working out my `user_id` but can't find it anywhere. (tried finding it in the html output or in any settings/cookies/etc)

Because of this my little "Am I rich?"-app has stalled in development... Would be fun to make it usable :)

**Comment by wizkid057** [comment]
testing some things now

**Comment by wizkid057** [comment]
merged and live

**Comment by wizkid057** [comment]
btw, the user_id is returned as part of getuseroptions currently, although I should probably expose some other way to do it.

**Comment by LinusU** [comment]
This might be me screwing up but I haven't gotten any data from `getacceptedcount` at all. I tried a bunch of random `user_id`s that I found in `getuseroptions` before but all yielded `getacceptedcount: No result`. This also happens when I put in my username, and since I have gotten paid on more than one occasion I guess that there really should be a result of my `getacceptedcount` or have I completely missed something? (Is it only for accepted mined bit coins and I just haven't found any yet?)

btw, I also tried used `getuseroptions` to get my `user_id` but it didn't list my username at all.

**Comment by wizkid057** [comment]
getacceptedcount returns the aggregated share count accepted by the pool, in terms of difficulty 1 shares.  It should work for any user with any number of accepted shares.

It looks like there is a bug (my fault) for if you dont specify a start date... i'll fix that.

**Pull request merged**
